#=============================================================================
# Travis NMODL settings
#=============================================================================

#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false
language: cpp
dist: bionic
osx_image: xcode10.2

#=============================================================================
# Common Packages
#=============================================================================
addons:
    apt:
        packages:
        - python3-pip
        - python-pip
        - python3-scipy
        - python-scipy
        - python3-tk
        - python-tk
        - libopenmpi-dev
        - openmpi-bin
        - libx11-dev
        - libxcomposite-dev
    homebrew:
        packages:
        - openmpi
        - xz
virtualenv:
    system_site_packages: true

#=============================================================================
# Configure build matrix and corresponding environment
#=============================================================================
env:
  global:
    - PYTHON="$(which python3)"
    - PIP="$(which pip3)"
    - INSTALL_DIR="$HOME/install"
  jobs:
    - CONFIG_OPTIONS="--without-x --without-paranrn --with-nrnpython=$(which python2) PYTHON_BLD=$(which python2)"
      PYTHON="$(which python2)"
      PIP="$(which pip2)"
    - CONFIG_OPTIONS="--without-x --without-paranrn --with-nrnpython=$PYTHON"
    - BUILD_MODE=cmake
      CMAKE_OPTION="-DNRN_ENABLE_MPI=ON -DNRN_ENABLE_INTERVIEWS=ON -DNRN_ENABLE_CORENEURON=ON"
    - BUILD_MODE=cmake
      CMAKE_OPTION="-DNRN_ENABLE_MPI=OFF -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_CORENEURON=ON"
    - BUILD_MODE=cmake
      CMAKE_OPTION="-DNRN_ENABLE_MPI=ON -DNRN_ENABLE_INTERVIEWS=ON -DNRN_ENABLE_CORENEURON=OFF"
    - BUILD_MODE=cmake
      NRN_ENABLE_PYTHON_DYNAMIC=ON
    - BUILD_MODE=cmake
      CMAKE_OPTION="-DNRN_ENABLE_PYTHON=OFF"

os:
#  - linux
  - osx

#=============================================================================
# Setup environment and Install dependencies
#=============================================================================
before_install:
  - echo $LANG
  - echo $LC_ALL
  - $CXX -v
  - export PYTHONPATH=$PYTHONPATH:$INSTALL_DIR/lib/python/;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ln -s /usr/local/bin/greadlink /usr/local/bin/readlink;
    fi
install:
  - $PIP install --user scipy matplotlib bokeh ipython cython --upgrade;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH=$HOME/Library/Python/3.7/bin:$HOME/Library/Python/2.7/bin:$PATH;
    fi

#=============================================================================
# Build, install and test
#=============================================================================
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export CONFIG_OPTIONS="$CONFIG_OPTIONS --with-readline=no";
    fi
  - if [ "$BUILD_MODE" == "cmake" ]; then
      if [ "$NRN_ENABLE_PYTHON_DYNAMIC" == "ON" ]; then
        export PYTHON2=$(which python2);
        export PYTHON3=$(which python3);
        export CMAKE_OPTION="-DNRN_ENABLE_PYTHON=ON -DNRN_ENABLE_PYTHON_DYNAMIC=ON -DNRN_PYTHON_DYNAMIC=${PYTHON2};${PYTHON3}";
      else
        export CMAKE_OPTION="$CMAKE_OPTION -DPYTHON_EXECUTABLE=${PYTHON}";
      fi;
      mkdir build && cd build;
      cmake $CMAKE_OPTION -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ..;
      cmake --build . -- -j 2;
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        echo $'[install]\nprefix='>src/nrnpython/setup.cfg;
      fi;
      make install;
      cd ..;
      export PATH=$INSTALL_DIR/bin:$PATH;
    else
      export PATH=$INSTALL_DIR/x86_64/bin:$PATH;
      ./travis_build.sh $INSTALL_DIR;
    fi
    # basic tests for cmake and autoconf build
  - neurondemo -nogui -c 'demo(4)' -c 'run()' -c 'quit()'
  - if [ "$NRN_ENABLE_PYTHON_DYNAMIC" == "ON" ]; then
      $PYTHON3 -c 'import neuron; neuron.test()' && $PYTHON2 -c 'import neuron; neuron.test()';
    else
      if [ "$CMAKE_OPTION" != "-DNRN_ENABLE_PYTHON=OFF" ]; then
        $PYTHON --version && $PYTHON -c 'import neuron; neuron.test()';
      fi;
    fi;
  - if [[ "$BUILD_MODE" != "cmake" && "$TRAVIS_OS_NAME" != "osx" ]]; then
      $PYTHON share/lib/python/neuron/rxdtests/run_all.py;
    fi;
